name: CI

on:
  push:
    paths:
      - 'Dockerfile'
  pull_request:
    paths:
      - 'Dockerfile'
  schedule:
    - cron: '0 0 1 * *' # Runs monthly on the 1st at midnight UTC
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-version:
    name: Check latest samapi version
    runs-on: ubuntu-latest
    outputs:
       CURRENT_VERSION: ${{ steps.current-version.outputs.CURRENT_VERSION }}
    steps:
      - name: Install Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/checkout@v4
        with:
          repository: 'ksugar/samapi'
      - name: Get current package version
        id: current-version
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          CURRENT_VERSION=$(poetry version | awk '{print $2}')
          echo "CURRENT_VERSION=$CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"
  docker:
    needs: check-version
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      CURRENT_VERSION: ${{ needs.check-version.outputs.CURRENT_VERSION }}
    name: Build and push Docker image
    strategy:
        fail-fast: true
        matrix:
          include:
            - python_version: "3.10"
              compatible_torch_version: "2.3.1"
              nvidia_cuda_tags: 11.8.0-base-ubuntu20.04
              pytorch_index_url: https://download.pytorch.org/whl/cu118
              cuda_tag: cu118
            - python_version: "3.10"
              compatible_torch_version: "2.3.1"
              nvidia_cuda_tags: 12.8.1-base-ubuntu20.04
              pytorch_index_url: https://download.pytorch.org/whl/cu128
              cuda_tag: cu128
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            NVIDIA_CUDA_TAG=${{ matrix.nvidia_cuda_tags }}
            PYTHON_VERSION=${{ matrix.python_version }}
            TORCH_INDEX_URL=${{ matrix.pytorch_index_url }}
            COMPATIBLE_TORCH_VERSION=${{ matrix.compatible_torch_version }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.CURRENT_VERSION }}-${{ matrix.cuda_tag }}
            ${{ matrix.cuda_tag == 'cu118' && format('{0}/{1}:latest', env.REGISTRY, env.IMAGE_NAME) || '' }}